include: package:very_good_analysis/analysis_options.3.0.2.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    depend_on_referenced_packages: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    unnecessary_to_list_in_spreads: true
    use_if_null_to_convert_nulls_to_bools: true
    use_test_throws_matchers: true
