name: flutter_value_notifier
description: Flutter Widgets that make it easy to implement state management patterns. Built to be used with the ValueNotifier.
version: 1.5.1
repository: https://github.com/robsonsilv4/flutter_value_notifier
issue_tracker: https://github.com/robsonsilv4/flutter_value_notifier/issues
documentation: https://github.com/robsonsilv4/flutter_value_notifier/blob/main/README.md
topics: [value-notifier, state-management, bloc, provider]
screenshots:
  - description: "The Flutter ValueNotifier logo."
    path: assets/logo.png

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
