name: flutter_value_notifier
description: Flutter Widgets that make it easy to implement state management patterns. Built to be used with the ValueNotifier class.
version: 1.4.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.2
