name: flutter_value_notifier

on: [pull_request, push]

jobs:
  run:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
